version: '3.3'
volumes:
  data:
services:
  postgres_gympoint:
    image: postgres
    container_name: postgres_gympoint
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gympoint
  mongo_gympoint:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
  redis_gympoint:
    image: redis:alpine
    ports:
      - '6379:6379'
