version: '3.3'
volumes:
  data:
services:
  db:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=gympoint
      - MYSQL_DATABASE=mysqlgympoint
redis:
  image: redis:alpine
  ports:
    - '6379:6379'
